### ISSUE TITLE
[BUG] Ackley3 is not optimal at reported value.

### ISSUE THREAD

**Issue by arthus701** [gugarosa/opytimark#1]
### Description
The [docs](https://opytimark.readthedocs.io/en/latest/api/opytimark.markers.two_dimensional.html#opytimark.markers.two_dimensional.Ackley3) report an optimal value of
-195.629028238419 @ (0.682584587365898, -0.36075325513719).

However:

```python
>>> import numpy as np
>>> from opytimark.markers import two_dimensional
>>> Ackley3 = two_dimensional.Ackley3()
>>> Ackley3(np.array([0.682584587365898, -0.36075325513719]))
-170.07756299785044
```
If it helps, my optimization algorithm converges to
-186.4112127112689 @ (4.79108613e-11, -6.77345749e-03)

### Steps to Reproduce
Run the python snippet from above
**Expected behavior:** The global minimum is where the docs report it.

**Actual behavior:** At the reported point, the function returns a larger value and there definitely exists better values, see above.

**Reproduces how often:** Every time

**Comment by gugarosa** [comment]
Hello @arthus701 ! I hope everything is all right with you.

Awesome, thank you very much for the feedback and the corrected values. I appreciate in you taking your time and coming here. I have just corrected Ackley3's tests and docs, it should be live in a few minutes.

I was wondering, which optimization algorithm did you use? Could you tell me, please?

Thank you again and best regards,
Gustavo.

**Comment by arthus701** [comment]
Hi @gugarosa,
I am using the python API of [dlib's LIPO-TR algorithm](http://blog.dlib.net/2017/12/a-global-optimization-algorithm-worth.html), wrapped in my own function to give it a scipy-like behavior.
I was testing it against scipy's Rosenbrock function, but wanted something else and google hinted me at your project, so I tried benchmarking against your Ackley3 implementation, which led to the issue...

Did you find out what went wrong with the reported optimum? I'm a little hesitant to try your other functions, as I don't see how reliable the reported optima are.

Cheers,
Arthus

**Comment by gugarosa** [comment]
Perfect, thank you!

Yes, I did found the problem and corrected it in the last commit. Please clone the package and install it locally instead of `pip install opytimark` as the changes have not been made in PyPI yet.

Actually the source where it was taken from (http://benchmarkfcns.xyz/benchmarkfcns/ackleyn3fcn.html) reports that the exponential uses `0.2`, but it is supposed to be `0.02` to achieve `-195.629028238419 @ (0.682584587365898, -0.36075325513719)`. On the other hand, https://arxiv.org/pdf/1308.4008.pdf describes a similar version, without the `-` signal, yet it has a different optimum point. Nevertheless, you should not be worried as this behavior will only happen with Ackley3 and Forrester. These functions do not have reported minimum points, they are just approximations.

Additionally, some functions, especially the n-dimensional ones, were evaluated and peer-reviewed in our following publication: https://www.sciencedirect.com/science/article/abs/pii/S1568494620303938. So they should be ready to go!

Nevertheless, if any other problems or concerns arise, please let me know.

Best regards,
Gustavo.
